"""Check the compiler-only installation and its signing boundary."""

import importlib.metadata
import importlib.util
from importlib.resources import files
from starkware.crypto.signature.signature import sign, verify, private_to_stark_key
from starkware.cairo.lang.compiler.cairo_compile import compile_cairo

if importlib.util.find_spec("ecdsa") is not None:
    raise RuntimeError("Compiler environment contains the removed ECDSA package")
if importlib.metadata.version("cairo-lang") != "0.14.3a3+snip36compiler1":
    raise RuntimeError("Expected the pinned compiler-only Cairo package")
if files("starkware.cairo.lang").joinpath("VERSION").read_text().strip() != "0.14.3a3":
    raise RuntimeError("Compiler-visible version changed")
try:
    sign(1, 1)
except RuntimeError as error:
    if "Signing is disabled" not in str(error):
        raise
else:
    raise RuntimeError("Compiler environment unexpectedly allows signing")

# Compile a real Cairo program, and exercise unchanged Stark-curve verification
# using a public fixture generated by the original pinned compiler.
program = compile_cairo("func main() {\n    return ();\n}\n", prime=2**251 + 17 * 2**192 + 1)
assert program.data
assert verify(1, 420423819908394641079278039288151495721101622431530179174315581048166880256,
              293905327363666551958107728095258322672969199051198726927803440602163689711,
              private_to_stark_key(1))
print("Compiler-only import, compilation, verification and signing boundary checks passed")
